# Generated by Django 5.1.7 on 2025-08-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, help_text='Course image for display', null=True, upload_to='course_images/'),
        ),
    ]
