# Generated by Django 5.1.7 on 2025-08-05 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100, verbose_name='Student Full Name')),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('grade_applying_for', models.CharField(choices=[('pre-montessori', 'Pre-Montessori'), ('montessori', 'Montessori'), ('grade1', 'Grade 1'), ('grade2', 'Grade 2'), ('grade3', 'Grade 3'), ('grade4', 'Grade 4'), ('grade5', 'Grade 5'), ('grade6', 'Grade 6'), ('grade7', 'Grade 7'), ('grade8', 'Grade 8'), ('grade9', 'Grade 9'), ('grade10', 'Grade 10')], max_length=20)),
                ('parent_name', models.CharField(max_length=100, verbose_name='Parent/Guardian Name')),
                ('parent_phone', models.CharField(max_length=20, verbose_name='Parent Phone Number')),
                ('parent_email', models.EmailField(max_length=254, verbose_name='Parent Email Address')),
                ('address', models.TextField(verbose_name='Home Address')),
                ('previous_school', models.CharField(blank=True, max_length=200, null=True, verbose_name='Previous School Name')),
                ('last_grade_attended', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Attended Grade')),
                ('special_requirements', models.TextField(blank=True, null=True, verbose_name='Special Requirements or Notes')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('is_processed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Admission Application',
                'verbose_name_plural': 'Admission Applications',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='AdmissionForm',
        ),
    ]
