# Generated by Django 5.1.7 on 2025-08-05 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_admissionapplication_delete_admissionform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissionapplication',
            name='address',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='grade_applying_for',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='last_grade_attended',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='parent_email',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='parent_name',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='parent_phone',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='previous_school',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='special_requirements',
        ),
        migrations.RemoveField(
            model_name='admissionapplication',
            name='student_name',
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='contact_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Number'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='date_of_birth_ad',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth (A.D.)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='date_of_birth_bs',
            field=models.CharField(blank=True, default='', help_text='e.g., 2057/02/15', max_length=20, verbose_name='Date of Birth (B.S.)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='full_name',
            field=models.CharField(default='', max_length=100, verbose_name='Full Name (Block Letters)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_contact',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name="Guardian's Contact Number"),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='guardian_name',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Name of Guardian'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='nationality',
            field=models.CharField(choices=[('nepali', 'Nepali'), ('indian', 'Indian'), ('other', 'Other')], default='nepali', max_length=20),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='other_qualification',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Any Other Qualification (Specify Organization)'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='permanent_address',
            field=models.TextField(blank=True, default='', verbose_name='Permanent Address'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admission_photos/', verbose_name='Profile Photo'),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='result_status',
            field=models.CharField(choices=[('passed', 'Passed'), ('awaited', 'Awaited')], default='passed', max_length=10),
        ),
        migrations.AddField(
            model_name='admissionapplication',
            name='temporary_address',
            field=models.TextField(blank=True, default='', verbose_name='Temporary Address'),
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='male', max_length=10),
        ),
        migrations.CreateModel(
            name='AcademicQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=200, verbose_name='Institution Name')),
                ('program', models.CharField(max_length=100, verbose_name='Program/Course')),
                ('symbol_number', models.CharField(max_length=50, verbose_name='Symbol Number')),
                ('passed_year', models.CharField(max_length=10, verbose_name='Passed Year')),
                ('division', models.CharField(choices=[('distinction', 'Distinction'), ('first', 'First Division'), ('second', 'Second Division'), ('third', 'Third Division')], max_length=20, verbose_name='Division')),
                ('percentage_cgpa', models.CharField(max_length=20, verbose_name='Percentage/CGPA')),
                ('major_subjects', models.TextField(verbose_name='Major Subjects')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_qualifications', to='base.admissionapplication')),
            ],
            options={
                'verbose_name': 'Academic Qualification',
                'verbose_name_plural': 'Academic Qualifications',
            },
        ),
        migrations.CreateModel(
            name='AdmissionDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=100, verbose_name='Document Name')),
                ('document_file', models.FileField(upload_to='admission_documents/', verbose_name='Document File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.admissionapplication')),
            ],
            options={
                'verbose_name': 'Admission Document',
                'verbose_name_plural': 'Admission Documents',
            },
        ),
    ]
