# Generated by Django 5.1.7 on 2025-08-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_admissionapplication_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='academicqualification',
            name='division',
        ),
        migrations.AlterField(
            model_name='admissionapplication',
            name='nationality',
            field=models.CharField(choices=[('nepali', 'Nepali'), ('other', 'Other')], default='nepali', max_length=20),
        ),
    ]
