# Generated by Django 5.1.7 on 2025-08-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_academicqualification_division_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploaded_at'], 'verbose_name_plural': 'Galleries'},
        ),
        migrations.RenameField(
            model_name='gallery',
            old_name='created_at',
            new_name='uploaded_at',
        ),
        migrations.RemoveField(
            model_name='gallery',
            name='description',
        ),
        migrations.AddField(
            model_name='gallery',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gallery_images/'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(help_text='Title of the gallery', max_length=200),
        ),
        migrations.DeleteModel(
            name='GalleryImage',
        ),
    ]
